# Generated by Django 6.0.3 on 2026-04-08 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Записи на курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.userprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Подробное описание курса (минимум 50 символов)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена в рублях от 0 до 1 000 000', max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть отрицательной'), django.core.validators.MaxValueValidator(1000000, message='Цена не может превышать 1 000 000')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False, help_text='Опубликовать курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Название курса (от 5 до 200 символов)', max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(help_text='Курс, на который записан студент', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'активна'), ('cancelled', 'отменена'), ('completed', 'завершена')], default='active', help_text='Статус записи на курс', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(help_text='Студент', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Основной контент урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='Название урока', max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(help_text='Номмер урока в курсе', validators=[django.core.validators.MinValueValidator(1, message='Номер должен быть не менее 1')]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Краткая информация о пользователе', validators=[django.core.validators.MaxLengthValidator(500, message='Описание не должно превышать 500 символов')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Фото профиля. Максимальный размер 2MB', upload_to='profile_images/'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
    ]
